

const char *instr[][2] = {
    {"ACI", "CE"},

    {"ADC A", "8F"},
    {"ADC B", "88"},
    {"ADC C", "89"},
    {"ADC D", "8A"},
    {"ADC E", "8B"},
    {"ADC H", "8C"},
    {"ADC L", "8D"},
    {"ADC M", "8E"},
    {"ADC A", "87"},
    {"ADC B", "80"},
    {"ADC C", "81"},
    {"ADC D", "82"},
    {"ADC E", "83"},
    {"ADC H", "84"},
    {"ADC L", "85"},
    {"ADC M", "86"},

    {"ADI", "C6"},

    {"ANA A", "A7"},
    {"ANA B", "A0"},
    {"ANA C", "A1"},
    {"ANA D", "A2"},
    {"ANA E", "A3"},
    {"ANA H", "A4"},
    {"ANA L", "A5"},
    {"ANA M", "A6"},
    {"ANA", "E6"},

    {"CALL", "CD"},
    {"CC", "DC"},
    {"CM", "FC"},
    {"CMA", "2F"},
    {"CMC", "3F"},
    {"CMP A", "BF"},
    {"CMP B", "B8"},
    {"CMP C", "B9"},
    {"CMP D", "BA"},
    {"CMP E", "BB"},
    {"CMP H", "BC"},
    {"CMP L", "BD"},
    {"CMP M", "BD"},

    {"CNC", "D4"},
    {"CNZ", "C4"},
    {"CP", "F4"},
    {"CPE", "EC"},
    {"CPI", "FE"},
    {"CPO", "E4"},
    {"CZ", "CC"},

    {"DDA", "27"},
    {"DAD B", "09"},
    {"DAD D", "19"},
    {"DAD H", "29"},
    {"DAD SP", "39"},

    {"DCR A", "3D"},
    {"DCR B", "05"},
    {"DCR C", "0D"},
    {"DCR D", "15"},
    {"DCR E", "1D"},
    {"DCR H", "25"},
    {"DCR L", "2D"},
    {"DCR M", "35"},

    {"DCX B", "0B"},
    {"DCX D", "1B"},
    {"DCX H", "2B"},
    {"DCX SP", "3B"},

    {"DI", "F3"},
    {"EI", "FB"},
    {"HLT", "76"},
    {"IN", "DB"},

    {"INR A", "3C"},
    {"INR B", "04"},
    {"INR C", "0C"},
    {"INR D", "14"},
    {"INR E", "1C"},
    {"INR H", "24"},
    {"INR L", "2C"},
    {"INR M", "34"},
    {"INX B", "03"},
    {"INX D", "13"},
    {"INX H", "23"},
    {"INX SP","33"},

    {"JC", "DA"},
    {"JM", "FA"},
    {"JMP", "C3"},
    {"JNC", "D2"},
    {"JNZ", "C2"},
    {"JP", "F2"},
    {"JPE", "EA"},
    {"JPO", "E2"},
    {"JZ", "CA"},

    {"LDA", "3A"},
    {"LDAX B", "0A"},
    {"LDAX D", "1A"},
    {"LHLD", "2A"},
    {"LXI B", "01"},
    {"LXI D", "11"},
    {"LXI H", "21"},
    {"LXI SP", "31"},

    {"MOV A, A", "7F"},
    {"MOV A, B", "78"},
    {"MOV A, C", "79"},
    {"MOV A, D", "7A"},
    {"MOV A, E", "7B"},
    {"MOV A, H", "7C"},
    {"MOV A, L", "7D"},
    {"MOV A, M", "7E"},

    {"MOV B, A", "47"},
    {"MOV B, B", "40"},
    {"MOV B, C", "41"},
    {"MOV B, D", "42"},
    {"MOV B, E", "43"},
    {"MOV B, H", "44"},
    {"MOV B, L", "45"},
    {"MOV B, M", "46"},

    {"MOV C, A", "4F"},
    {"MOV C, B", "48"},
    {"MOV C, C", "49"},
    {"MOV C, D", "4A"},
    {"MOV C, E", "4B"},
    {"MOV C, H", "4C"},
    {"MOV C, L", "4D"},
    {"MOV C, M", "4E"},

    {"MOV D, A", "57"},
    {"MOV D, B", "50"},
    {"MOV D, C", "51"},
    {"MOV D, D", "52"},
    {"MOV D, E", "53"},
    {"MOV D, H", "54"},
    {"MOV D, L", "55"},
    {"MOV D, M", "56"},

    {"MOV E, A", "5F"},
    {"MOV E, B", "58"},
    {"MOV E, C", "59"},
    {"MOV E, D", "5A"},
    {"MOV E, E", "5B"},
    {"MOV E, H", "5C"},
    {"MOV E, L", "5D"},
    {"MOV E, M", "5E"},

    {"MOV H, A", "67"},
    {"MOV H, B", "60"},
    {"MOV H, C", "61"},
    {"MOV H, D", "62"},
    {"MOV H, E", "63"},
    {"MOV H, H", "64"},
    {"MOV H, L", "65"},
    {"MOV H, M", "66"},

    {"MOV L, A", "6F"},
    {"MOV L, B", "68"},
    {"MOV L, C", "69"},
    {"MOV L, D", "6A"},
    {"MOV L, E", "6B"},
    {"MOV L, H", "6C"},
    {"MOV L, L", "6D"},
    {"MOV L, M", "6E"},

    {"MOV M, A", "77"},
    {"MOV M, B", "70"},
    {"MOV M, C", "71"},
    {"MOV M, D", "72"},
    {"MOV M, E", "73"},
    {"MOV M, H", "74"},
    {"MOV M, L", "75"},

    
};